# Generated by Django 4.2.7 on 2026-04-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_add_chunk_model"),
        ("app", "0002_taskdocument"),
    ]

    operations = []
